Fix email addresses not being add when user is created
revsys/django-test-plus pull request #207
Opened 2023-07-01 20:15 UTC by epicserve

2023-07-01 20:18 UTC, epicserve commented
This PR fixes #206. I'm happy to make edits or go in a different direction.

2023-07-08 18:13 UTC, epicserve commented
@jefftriplett or @frankwiles, just wondering if either of you will have bandwidth to review and move this forward. There is also another bug caused by the most resent release that has PR ready.

2023-07-08 20:57 UTC, jefftriplett requested changes

2023-07-08 20:57 UTC, jefftriplett commented on test_plus/test.py
> +        user_data = {USERNAME_FIELD: username}
Let's switch these two lines to keep the logic grouping together based on the variable names:

```suggestion
        user_data = {USERNAME_FIELD: username}
        EMAIL_FIELD = getattr(User, 'EMAIL_FIELD', None)
```

2023-07-09 13:04 UTC, epicserve commented
@jefftriplett done ✅

2023-07-09 19:54 UTC, jefftriplett approved these changes
🎉  Looks good to me. I'll defer the merge and final judgement to @frankwiles because I don't have deploy access.

2023-07-11 11:35 UTC, frankwiles commented
Thanks @epicserve doing a release right now.

2023-07-11 11:35 UTC, merged